require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/user_books", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # UserBook. As you add validations to UserBook, be sure to
  # adjust the attributes here as well.
  let(:user) { User.create!(username: "axolotl") }
  let(:book) { Book.create!(title: "The Hobbit", author: "J.R.R. Tolkien", price: 9.99, published_date: Date.new(1937, 9, 21)) }

  let(:valid_attributes) {
    { user_id: user.id, book_id: book.id }
  }

  let(:invalid_attributes) {
    { user_id: nil, book_id: book.id }
  }

  describe "GET /index" do
    it "renders a successful response" do
      UserBook.create! valid_attributes
      get user_books_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      user_book = UserBook.create! valid_attributes
      get user_book_url(user_book)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_user_book_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      user_book = UserBook.create! valid_attributes
      get edit_user_book_url(user_book)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new UserBook" do
        expect {
          post user_books_url, params: { user_book: valid_attributes }
        }.to change(UserBook, :count).by(1)
      end

      it "redirects to the created user_book" do
        post user_books_url, params: { user_book: valid_attributes }
        expect(response).to redirect_to(user_book_url(UserBook.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new UserBook" do
        expect {
          post user_books_url, params: { user_book: invalid_attributes }
        }.to change(UserBook, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post user_books_url, params: { user_book: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:other_book) { Book.create!(title: "The Secret of Life", author: "J.R.R. Tolkien", price: 5.99, published_date: Date.new(1940, 1, 1)) }
      let(:new_attributes) {
        { book_id: other_book.id }
      }

      it "updates the requested user_book" do
        user_book = UserBook.create! valid_attributes
        patch user_book_url(user_book), params: { user_book: new_attributes }
        user_book.reload
        expect(user_book.book).to eq(other_book)
      end

      it "redirects to the user_book" do
        user_book = UserBook.create! valid_attributes
        patch user_book_url(user_book), params: { user_book: new_attributes }
        user_book.reload
        expect(response).to redirect_to(user_book_url(user_book))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        user_book = UserBook.create! valid_attributes
        patch user_book_url(user_book), params: { user_book: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested user_book" do
      user_book = UserBook.create! valid_attributes
      expect {
        delete user_book_url(user_book)
      }.to change(UserBook, :count).by(-1)
    end

    it "redirects to the user_books list" do
      user_book = UserBook.create! valid_attributes
      delete user_book_url(user_book)
      expect(response).to redirect_to(user_books_url)
    end
  end
end
